### ISSUE TITLE
Foundry VTT Release 10 reports errors for module

### ISSUE THREAD

**Issue by ServerOnTheMove** [MadManNBlueBox/wands#21]
I want to start by saying "Thank You" for the effort to put this together.

I have tried to install the module on FVTT R10 and get a number of warnings in the console:

setup.js:145 [wands] The module "wands" contains compendium pack data which uses the deprecated "entity" field which must be migrated to "type"
setup.js:145 [wands] The module "wands" contains dependencies using "name" which is deprecated in favor of "id"
setup.js:145 [wands] The module "wands" contains "dependencies" which is deprecated in favor of "relationships.requires"
setup.js:145 [wands] module "wands" contains "system" which is deprecated in favor of "relationships.systems"
setup.js:145 [wands] The module "wands" is using the old flat core compatibility fields which are deprecated in favor of the new setup.js:145 [wands] The module "wands" is using "name" which is deprecated in favor of "id"
setup.js:145 [moulinette-imagesearch] The module "moulinette-imagesearch" is using "name" which is deprecated in favor of "id"

**Comment by MadManNBlueBox** [comment]
Thank you for pointing out these issues. However I am awear of them and have plans to fix them. I do this as a hobby on my free time and right now work has me pretty busy. I'm hoping things let up in the next month or so and I am able to resolve until then I recommend using V9.

To give a little clarification on why it say it's compatible with v10 before you install it. I did test with V10 very early on before they put in the core changes to the API and so everything looked like it was fine. I apologize for any confusion that may have cause and hope using V9 works for you for now.

**Comment by ServerOnTheMove** [comment]
Hi,
Thanks heaps for taking the time to respond, and I fully understand having to juggle a hobby next to doing your daily commitments.

I have just started looking at FVTT, and your module was quite interesting as my little ones are Harry Potter fans.

I will keep an eye out for the progress of this module as it happens over the next time.
It would have been good if the FVTT APIs had been kept backwards compatible for at least the current release - 1 ;-)

Have a great time, and hope all is well and healthy

Regards,
Dante

**Comment by MadManNBlueBox** [comment]
Just updated the module to work with V10 and the latest version of DnD5e. Let me know if you have any issues but I am going to close this issue for now.
