### ISSUE TITLE
Can't update to 0.9.2

### ISSUE THREAD

**Issue by RinVindor** [MadManNBlueBox/wands#25]
![image](https://user-images.githubusercontent.com/12647469/195144819-8338d02d-73f3-4502-97cd-3ed91b278129.png)

**Comment by MadManNBlueBox** [comment]
What version of Foundry are you on?

**Comment by MadManNBlueBox** [comment]
Figured out the issue. Forgot to put the module and zip file in the release. It should work for you now.
